/* Files */
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS DATA;
DROP TABLE IF EXISTS SMSS;
DROP TABLE IF EXISTS TARGETS;
DROP TABLE IF EXISTS AUDITLOGS;
DROP TABLE IF EXISTS CONFIG;


/* SMS */
CREATE TABLE SMSS(
    ID SERIAL PRIMARY KEY,
    SENDER VARCHAR(100),
    RECEIVER VARCHAR(100),
    MSG VARCHAR(5000),
    RECEIVE_DATE TIMESTAMP,
    COUNTRY VARCHAR(100),
    URL VARCHAR(1000),
    DOMAIN VARCHAR(500),
    SOURCE VARCHAR(200),
    DATA_HANDLED BOOLEAN NOT NULL
);

CREATE TABLE DATA(
    ID SERIAL PRIMARY KEY,
    SMS_DATA VARCHAR(32000),
    SMS_ID INT REFERENCES SMSS(ID)
);

CREATE TABLE TARGETS(
    ID SERIAL PRIMARY KEY,
    DOMAIN VARCHAR(32000) UNIQUE,
    IS_LEGAL BOOLEAN NOT NULL,
    IS_AUTOMATED BOOLEAN NOT NULL,
    IS_INTERESTING BOOLEAN NOT NULL,
    IS_INTERESTING_DESC VARCHAR(1000)
);

CREATE TABLE AUDITLOGS(
    ID SERIAL PRIMARY KEY,
    HTTP_REQ_DATE TIMESTAMP,
    HTTP_VERB VARCHAR(32000), 
    HTTP_REQ VARCHAR(32000),
    HTTP_RESP_CODE VARCHAR(32000),
    HTTP_RESP_CONTENT VARCHAR(32000)
);

CREATE TABLE CONFIG(
    ID SERIAL PRIMARY KEY,
    IS_TARGETS_IMPORTED BOOLEAN NOT NULL,
    MODE VARCHAR(30) DEFAULT 'PASSIVE',
    LOCK BOOLEAN  NOT NULL
);
INSERT INTO CONFIG(IS_TARGETS_IMPORTED, LOCK) VALUES('f', 'f');

CREATE TABLE USERS(
    ID SERIAL PRIMARY KEY,
    USERNAME VARCHAR(32) NOT NULL,
    PASSWORD VARCHAR(256) NOT NULL,
    ROLE VARCHAR(32)
);


ALTER DATABASE postgres SET datestyle TO 'GERMAN,MDY';