version: '3'
services:
    # Database
    database:
        image: postgres
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=FileExposer
            - POSTGRES_USER=postgres
        volumes:
            - ./database/init:/docker-entrypoint-initdb.d/
            - exports:/etc/data/exports

    # Redis server
    redisserver:
        image: redis:latest
        ports:
            - 6379:6379

    # Redis queue
    fetcher_worker:
        image: opensms:latest
        depends_on:
            - redisserver
            - database
        command: rq worker --url redis://redisserver:6379
    
    data_worker:
        image: opensms:latest
        depends_on:
            - fetcher_worker
            - database
        command: rq worker --url redis://redisserver:6379

    # Web server
    opensms:
        image: opensms:latest
        depends_on:
            - redisserver
            - database
        build: .
        restart: on-failure
        ports:
            - 9000:9000
        volumes:
            - exports:/etc/data/exports
    
volumes:
    exports: