services:
    # Database
    database:
        image: postgres
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=FileExposer
            - POSTGRES_USER=postgres
        volumes:
            - ./database/init:/docker-entrypoint-initdb.d/
            - exports:/etc/data/exports
            - imports:/etc/data/imports
        healthcheck:
            test: ["CMD", "psql", "-U", "postgres", "-d", "postgres", "-c", "SELECT * FROM smss LIMIT 1"]
            interval: 30s
            timeout: 10s
            retries: 5
        networks:
            - common

    # Redis server (queue)
    redisserver:
        image: redis:latest
        ports:
            - 6379:6379
        command: redis-server --loglevel debug
        networks:
            - common
        dns: 1.1.1.1

    # Redis workers
    fetcher_worker:
        image: opensms:latest
        volumes:
            - exports:/etc/data/exports
            - imports:/etc/data/imports
        depends_on:
            - redisserver
            - database
        command: rq worker --name fetcher --url redis://redisserver:6379
        networks:
            - common
        dns: 1.1.1.1
    
    data_worker:
        image: opensms:latest
        volumes:
            - exports:/etc/data/exports
            - imports:/etc/data/imports
        depends_on:
            - fetcher_worker
            - database
        command: rq worker --name data --url redis://redisserver:6379
        networks:
            - common
        dns: 1.1.1.1

    # Web server
    smsexplorer:
        image: opensms:latest
        depends_on:
            - redisserver
            - database
        build: .
        restart: on-failure
        ports:
            - 80:9000
        volumes:
            - exports:/etc/data/exports
            - imports:/etc/data/imports
        networks:
            - common
        dns: 1.1.1.1

networks:
    common:
        driver: host

volumes:
    exports:
    imports: